### ISSUE TITLE
Your shit is wrong

### ISSUE THREAD

**Issue by blurer** [rtyner/homelab#1]
Need to fix: https://github.com/rtyner/homelab/blob/main/ansible/ubuntu_setup.yml

```
  - name: bashrc
 ansible.builtin.shell:
 cmd: wget https://raw.githubusercontent.com/rtyner/dotfiles/master/.bashrc -O /home/rt/.bashrc && chown rt:rt /home/rt/.bashrc && chmod 644 /home/rt/.bashrc
```

With this:
```
  - name: bashrc
    get_url: 
      url: https://raw.githubusercontent.com/rtyner/dotfiles/master/.bashrc
      dest: /home/rt/
```
